<?php

declare(strict_types=1);

namespace Eolica\Hubspot\Api\Marketing\V2026_09\TransactionalEmails;

use Eolica\Hubspot\Http\Meta;
use Eolica\Hubspot\Http\Response;

final readonly class SendResponse
{
    /**
     * @param 'CANCELED'|'COMPLETE'|'PENDING'|'PROCESSING' $status
     * @param 'ADDRESS_LIST_BOMBED'|'ADDRESS_ONLY_ACCEPTED_ON_PROD'|'ADDRESS_OPTED_OUT'|'ATTACHMENT_DOWNLOAD_QUEUE_FULL'|'BLOCKED_ADDRESS'|'BLOCKED_DOMAIN'|'BRAND_RECIPIENT_FATIGUE_SUPPRESSED'|'CAMPAIGN_CANCELLED'|'CANCELLED_ABUSE'|'CONTACT_VIEW_PERMISSION'|'CORRUPT_INPUT'|'EMAIL_DISABLED'|'EMAIL_UNCONFIRMED'|'GDPR_DOI_ENABLED'|'GRAYMAIL_SUPPRESSED'|'HUBL_LIMIT_EXCEEDED'|'IDEMPOTENT_FAIL'|'IDEMPOTENT_IGNORE'|'INVALID_APP_ID_ATTRIBUTION'|'INVALID_FROM_ADDRESS'|'INVALID_TO_ADDRESS'|'LOW_CONTACT_QUALITY_SCORE'|'MARKETING_ACTIVATION_DISALLOWED'|'MISSING_CONTENT'|'MISSING_REQUIRED_PARAMETER'|'MISSING_TEMPLATE_PROPERTIES'|'MTA_IGNORE'|'NON_MARKETABLE_CONTACT'|'PORTAL_AUTHENTICATION_FAILURE'|'PORTAL_EXPIRED'|'PORTAL_MISSING_MARKETING_SCOPE'|'PORTAL_NOT_AUTHORIZED_FOR_APPLICATION'|'PORTAL_OVER_LIMIT'|'PORTAL_SUSPENDED'|'PREVIOUS_SPAM'|'PREVIOUSLY_BOUNCED'|'PREVIOUSLY_UNSUBSCRIBED_BRAND'|'PREVIOUSLY_UNSUBSCRIBED_BUSINESS_UNIT'|'PREVIOUSLY_UNSUBSCRIBED_MESSAGE'|'PREVIOUSLY_UNSUBSCRIBED_PORTAL'|'QUARANTINED_ADDRESS'|'QUEUED'|'RECIPIENT_FATIGUE_SUPPRESSED'|'SENT'|'TEMPLATE_RENDER_EXCEPTION'|'THROTTLED'|'TOO_MANY_RECIPIENTS'|'UBB_GOVERNANCE_MISSING'|'UNCONFIGURED_SENDING_DOMAIN'|'UNDELIVERABLE'|'VALIDATION_FAILED'|null $sendResult
     * @param array{id: string, created: string}|null $eventId
     */
    private function __construct(
        public string $status,
        public string $statusId,
        public ?string $sendResult,
        public ?string $message,
        public ?string $startedAt,
        public ?string $completedAt,
        public ?array $eventId,
        public Meta $meta,
    ) {}

    /**
     * @param Response<array{status: 'CANCELED'|'COMPLETE'|'PENDING'|'PROCESSING', statusId: string, sendResult?: 'ADDRESS_LIST_BOMBED'|'ADDRESS_ONLY_ACCEPTED_ON_PROD'|'ADDRESS_OPTED_OUT'|'ATTACHMENT_DOWNLOAD_QUEUE_FULL'|'BLOCKED_ADDRESS'|'BLOCKED_DOMAIN'|'BRAND_RECIPIENT_FATIGUE_SUPPRESSED'|'CAMPAIGN_CANCELLED'|'CANCELLED_ABUSE'|'CONTACT_VIEW_PERMISSION'|'CORRUPT_INPUT'|'EMAIL_DISABLED'|'EMAIL_UNCONFIRMED'|'GDPR_DOI_ENABLED'|'GRAYMAIL_SUPPRESSED'|'HUBL_LIMIT_EXCEEDED'|'IDEMPOTENT_FAIL'|'IDEMPOTENT_IGNORE'|'INVALID_APP_ID_ATTRIBUTION'|'INVALID_FROM_ADDRESS'|'INVALID_TO_ADDRESS'|'LOW_CONTACT_QUALITY_SCORE'|'MARKETING_ACTIVATION_DISALLOWED'|'MISSING_CONTENT'|'MISSING_REQUIRED_PARAMETER'|'MISSING_TEMPLATE_PROPERTIES'|'MTA_IGNORE'|'NON_MARKETABLE_CONTACT'|'PORTAL_AUTHENTICATION_FAILURE'|'PORTAL_EXPIRED'|'PORTAL_MISSING_MARKETING_SCOPE'|'PORTAL_NOT_AUTHORIZED_FOR_APPLICATION'|'PORTAL_OVER_LIMIT'|'PORTAL_SUSPENDED'|'PREVIOUS_SPAM'|'PREVIOUSLY_BOUNCED'|'PREVIOUSLY_UNSUBSCRIBED_BRAND'|'PREVIOUSLY_UNSUBSCRIBED_BUSINESS_UNIT'|'PREVIOUSLY_UNSUBSCRIBED_MESSAGE'|'PREVIOUSLY_UNSUBSCRIBED_PORTAL'|'QUARANTINED_ADDRESS'|'QUEUED'|'RECIPIENT_FATIGUE_SUPPRESSED'|'SENT'|'TEMPLATE_RENDER_EXCEPTION'|'THROTTLED'|'TOO_MANY_RECIPIENTS'|'UBB_GOVERNANCE_MISSING'|'UNCONFIGURED_SENDING_DOMAIN'|'UNDELIVERABLE'|'VALIDATION_FAILED'|null, message?: string|null, startedAt?: string|null, completedAt?: string|null, eventId?: array{id: string, created: string}|null}> $response
     */
    public static function fromResponse(Response $response): self
    {
        return new self(
            $response->data['status'],
            $response->data['statusId'],
            $response->data['sendResult'] ?? null,
            $response->data['message'] ?? null,
            $response->data['startedAt'] ?? null,
            $response->data['completedAt'] ?? null,
            $response->data['eventId'] ?? null,
            $response->meta,
        );
    }
}
